import { getDefaultSubscriptionPackageBlueprints } from '@/lib/plans';
import { hashPassword } from '@/server/store/passwords';
import type { StoreState } from '@/server/store/types';

const now = '2026-04-04T09:00:00.000Z';

export const demoCredentials = {
  superAdmin: { business: 'platform', username: 'aurelius', password: 'Aurelius@2026' },
  shopAdmin: { business: 'royal-fades', username: 'naomi', password: 'Naomi@123' },
  staffBrian: { business: 'royal-fades', username: 'brian', password: 'Brian@123' },
  staffMercy: { business: 'royal-fades', username: 'mercy', password: 'Mercy@123' },
  secondAdmin: { business: 'golden-chair', username: 'sasha', password: 'Sasha@123' },
} as const;

export function createSeedStore(): StoreState {
  const packageBlueprints = getDefaultSubscriptionPackageBlueprints();
  const basicPackage = packageBlueprints.find((item) => item.code === 'basic')!;
  const platinumPackage = packageBlueprints.find((item) => item.code === 'platinum')!;

  return {
    tenants: [
      {
        id: 'tenant-royal-fades',
        name: 'Royal Fades & Beauty Lounge',
        ownerName: 'Naomi Wanjiru',
        slug: 'royal-fades',
        logoUrl: null,
        motto: 'Sharp looks. Warm service. Every visit.',
        address: 'Tom Mboya Street, Nairobi CBD',
        storeNumber: 'RF-001',
        timezone: 'Africa/Nairobi',
        countryCode: 'KE',
        currencyCode: 'KES',
        status: 'active',
        loyaltyProgram: {
          isEnabled: true,
          spendThreshold: 10000,
          rewardType: 'subsidized_service',
          rewardValue: 500,
          rewardLabel: 'KES 500 loyalty credit',
          notes: 'Customers unlock a KES 500 discount after spending KES 10,000 in total.',
        },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'tenant-golden-chair',
        name: 'Golden Chair Studio',
        ownerName: 'Sasha Njeri',
        slug: 'golden-chair',
        logoUrl: null,
        motto: 'Style delivered with quiet confidence.',
        address: 'Moi Avenue, Nakuru',
        storeNumber: 'GC-014',
        timezone: 'Africa/Nairobi',
        countryCode: 'KE',
        currencyCode: 'KES',
        status: 'active',
        loyaltyProgram: {
          isEnabled: false,
          spendThreshold: 12000,
          rewardType: 'free_service',
          rewardValue: 0,
          rewardLabel: 'Complimentary service',
          notes: 'Disabled until the tenant is ready to launch loyalty rewards.',
        },
        createdAt: now,
        updatedAt: now,
      },
    ],
    users: [
      {
        id: 'user-super-admin',
        tenantId: null,
        role: 'super_admin',
        fullName: 'House Aurelius',
        username: demoCredentials.superAdmin.username,
        email: 'admin@hapos.app',
        password: hashPassword(demoCredentials.superAdmin.password),
        passwordUpdatedAt: now,
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'user-shop-admin',
        tenantId: 'tenant-royal-fades',
        role: 'shop_admin',
        fullName: 'Naomi Wanjiru',
        username: demoCredentials.shopAdmin.username,
        email: 'naomi@royalfades.example',
        phone: '+254711000001',
        password: hashPassword(demoCredentials.shopAdmin.password),
        passwordUpdatedAt: now,
        isActive: true,
        commissionType: 'percentage',
        commissionValue: 0,
        commissionNotes: 'Admin oversight role',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'user-staff-brian',
        tenantId: 'tenant-royal-fades',
        role: 'staff',
        fullName: 'Brian Otieno',
        username: demoCredentials.staffBrian.username,
        email: 'brian@royalfades.example',
        phone: '+254711000002',
        password: hashPassword(demoCredentials.staffBrian.password),
        passwordUpdatedAt: now,
        isActive: true,
        commissionType: 'percentage',
        commissionValue: 35,
        commissionNotes: '35% on recorded services',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'user-staff-mercy',
        tenantId: 'tenant-royal-fades',
        role: 'staff',
        fullName: 'Mercy Atieno',
        username: demoCredentials.staffMercy.username,
        email: 'mercy@royalfades.example',
        phone: '+254711000003',
        password: hashPassword(demoCredentials.staffMercy.password),
        passwordUpdatedAt: now,
        isActive: true,
        commissionType: 'fixed',
        commissionValue: 900,
        commissionNotes: 'Fixed braid commission',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'user-golden-admin',
        tenantId: 'tenant-golden-chair',
        role: 'shop_admin',
        fullName: 'Sasha Njeri',
        username: demoCredentials.secondAdmin.username,
        email: 'sasha@goldenchair.example',
        phone: '+254711000010',
        password: hashPassword(demoCredentials.secondAdmin.password),
        passwordUpdatedAt: now,
        isActive: true,
        commissionType: 'percentage',
        commissionValue: 0,
        commissionNotes: 'Admin oversight role',
        createdAt: now,
        updatedAt: now,
      },
    ],
    customers: [
      {
        id: 'customer-1',
        tenantId: 'tenant-royal-fades',
        name: 'Kevin Mwangi',
        phone: '0711000101',
        phoneE164: '+254711000101',
        marketingOptIn: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'customer-2',
        tenantId: 'tenant-royal-fades',
        name: 'Aisha Noor',
        phone: '0711000102',
        phoneE164: '+254711000102',
        marketingOptIn: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'customer-3',
        tenantId: 'tenant-royal-fades',
        name: 'Daniel Kiptoo',
        phone: '0711000103',
        phoneE164: '+254711000103',
        marketingOptIn: false,
        createdAt: now,
        updatedAt: now,
      },
    ],
    services: [
      {
        id: 'service-haircut',
        tenantId: 'tenant-royal-fades',
        name: 'Signature Haircut',
        price: 800,
        description: 'Fade, trim, and finishing',
        imageUrl: null,
        commissionType: 'percentage',
        commissionValue: 35,
        durationMinutes: 35,
        isActive: true,
        createdBy: 'user-shop-admin',
        updatedBy: 'user-shop-admin',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'service-shave',
        tenantId: 'tenant-royal-fades',
        name: 'Executive Shave',
        price: 500,
        description: 'Hot towel shave',
        imageUrl: null,
        commissionType: 'percentage',
        commissionValue: 30,
        durationMinutes: 20,
        isActive: true,
        createdBy: 'user-shop-admin',
        updatedBy: 'user-shop-admin',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'service-braids',
        tenantId: 'tenant-royal-fades',
        name: 'Knotless Braids',
        price: 3500,
        description: 'Medium size',
        imageUrl: null,
        commissionType: 'fixed',
        commissionValue: 900,
        durationMinutes: 120,
        isActive: true,
        createdBy: 'user-shop-admin',
        updatedBy: 'user-shop-admin',
        createdAt: now,
        updatedAt: now,
      },
    ],
    products: [
      {
        id: 'product-pomade',
        tenantId: 'tenant-royal-fades',
        name: 'Pomade',
        unitCost: 120,
        description: 'Hair styling pomade',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'product-beard-oil',
        tenantId: 'tenant-royal-fades',
        name: 'Beard Oil',
        unitCost: 180,
        description: 'Conditioning beard oil',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
    serviceRecords: [
      {
        id: 'record-1',
        tenantId: 'tenant-royal-fades',
        customerId: 'customer-1',
        staffId: 'user-staff-brian',
        serviceId: 'service-haircut',
        serviceName: 'Signature Haircut',
        isCustomService: false,
        price: 800,
        description: 'Low fade and beard line-up',
        commissionType: 'percentage',
        commissionValue: 35,
        commissionAmount: 280,
        productUsages: [{ productId: 'product-pomade', quantity: 1, unitCost: 120 }],
        performedAt: '2026-04-04T07:45:00.000Z',
        recordedBy: 'user-staff-brian',
        createdAt: '2026-04-04T07:45:00.000Z',
      },
      {
        id: 'record-2',
        tenantId: 'tenant-royal-fades',
        customerId: 'customer-2',
        staffId: 'user-staff-mercy',
        serviceId: 'service-braids',
        serviceName: 'Knotless Braids',
        isCustomService: false,
        price: 3500,
        description: 'Medium knotless refresh',
        commissionType: 'fixed',
        commissionValue: 900,
        commissionAmount: 900,
        productUsages: [{ productId: 'product-beard-oil', quantity: 1, unitCost: 180 }],
        performedAt: '2026-04-03T14:30:00.000Z',
        recordedBy: 'user-staff-mercy',
        createdAt: '2026-04-03T14:30:00.000Z',
      },
      {
        id: 'record-3',
        tenantId: 'tenant-royal-fades',
        customerId: 'customer-3',
        staffId: 'user-staff-brian',
        serviceId: null,
        serviceName: 'Home Service Beard Trim',
        isCustomService: true,
        price: 1000,
        description: 'Custom off-menu callout service',
        commissionType: 'percentage',
        commissionValue: 35,
        commissionAmount: 350,
        productUsages: [],
        performedAt: '2026-04-02T16:10:00.000Z',
        recordedBy: 'user-staff-brian',
        createdAt: '2026-04-02T16:10:00.000Z',
      },
    ],
    expenses: [
      {
        id: 'expense-1',
        tenantId: 'tenant-royal-fades',
        category: 'Stock',
        description: 'Hair products replenishment',
        amount: 5200,
        expenseDate: '2026-04-02',
        createdBy: 'user-shop-admin',
        createdAt: now,
      },
      {
        id: 'expense-2',
        tenantId: 'tenant-royal-fades',
        category: 'Utilities',
        description: 'Water and electricity',
        amount: 3100,
        expenseDate: '2026-04-01',
        createdBy: 'user-shop-admin',
        createdAt: now,
      },
    ],
    subscriptionPackages: [
      {
        id: 'package-basic',
        ...basicPackage,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'package-platinum',
        ...platinumPackage,
        createdAt: now,
        updatedAt: now,
      },
    ],
    subscriptions: [
      {
        id: 'sub-royal-fades',
        tenantId: 'tenant-royal-fades',
        packageId: 'package-platinum',
        planCode: 'platinum',
        status: 'active',
        startsAt: '2026-03-01T00:00:00.000Z',
        endsAt: '2026-04-30T23:59:59.000Z',
        amount: 12500,
        currencyCode: 'KES',
        autoRenew: true,
        paymentTerms: 'Paid monthly in advance',
        updatedAt: now,
      },
      {
        id: 'sub-golden-chair',
        tenantId: 'tenant-golden-chair',
        packageId: 'package-basic',
        planCode: 'basic',
        status: 'active',
        startsAt: '2026-03-15T00:00:00.000Z',
        endsAt: '2026-04-14T23:59:59.000Z',
        amount: 8500,
        currencyCode: 'KES',
        autoRenew: false,
        paymentTerms: 'Manual renewal every month',
        updatedAt: now,
      },
    ],
    smsLogs: [
      {
        id: 'sms-1',
        tenantId: 'tenant-royal-fades',
        customerId: 'customer-1',
        smsType: 'thank_you',
        recipientPhone: '+254711000101',
        message: 'Thanks for visiting Royal Fades & Beauty Lounge, Kevin.',
        status: 'sent',
        sentAt: '2026-04-04T07:46:00.000Z',
        createdAt: '2026-04-04T07:46:00.000Z',
      },
    ],
    commissionPayouts: [
      {
        id: 'payout-1',
        tenantId: 'tenant-royal-fades',
        staffId: 'user-staff-brian',
        amount: 5400,
        periodStart: '2026-03-01',
        periodEnd: '2026-03-31',
        paidAt: '2026-04-01T09:00:00.000Z',
        createdAt: '2026-04-01T09:00:00.000Z',
      },
    ],
    sessions: [],
    customerSessions: [],
    marketplaceAds: [
      {
        id: 'ad-royal-pomade',
        tenantId: 'tenant-royal-fades',
        title: 'Premium grooming kit bundles',
        body: 'Royal Fades is offering bundled grooming kits with pomade, beard oil, and a home-care trim voucher for repeat clients.',
        contactName: 'Naomi Wanjiru',
        contactPhone: '+254711000001',
        imageUrl: null,
        status: 'approved',
        approvalNotes: 'Brand-safe and ready for the marketplace board.',
        createdBy: 'user-shop-admin',
        approvedBy: 'user-super-admin',
        approvedAt: '2026-04-03T10:00:00.000Z',
        createdAt: '2026-04-02T12:00:00.000Z',
        updatedAt: '2026-04-03T10:00:00.000Z',
      },
    ],
    customerOrders: [
      {
        id: 'order-1',
        tenantId: 'tenant-royal-fades',
        customerId: 'customer-1',
        serviceId: 'service-shave',
        serviceName: 'Executive Shave',
        requestedStaffId: 'user-staff-brian',
        requestedName: 'Kevin Mwangi',
        requestedPhone: '+254711000101',
        notes: 'Would like the evening slot if available.',
        status: 'pending',
        requestedAt: '2026-04-04T08:10:00.000Z',
        statusUpdatedAt: null,
        createdAt: '2026-04-04T08:10:00.000Z',
      },
    ],
  };
}
