"use strict";
const { createBusinessTool } = require("./baseBusinessTool");
function createRevenueByEmployeeTool(repo) {
  return createBusinessTool({ id: "revenueByEmployee", name: "Revenue by Employee", description: "Break down revenue generated by each employee.", category: "Revenue", risk: "low", repo, method: "getRevenueByEmployee" });
}
module.exports = { createRevenueByEmployeeTool };