properties
MYAPP_RELEASE_STORE_FILE= my-release-key.jks.
MYAPP_RELEASE_STORE_PASSWORD=The-doom-of-all-men-is-quiting
MYAPP_RELEASE_KEY_ALIAS=your_key_alias
MYAPP_RELEASE_KEY_PASSWORD=But-i-will-always-advance