/**
 * Analytics capabilities. These delegate to the existing AI tool
 * implementations (same canonical BI operations, same tenant scoping) — the
 * unified registry advertises them without duplicating any logic. Fictional
 * analytics (invoice/branch/payment-method groupings over nonexistent fields)
 * are deliberately absent here; see the CJS catalog cleanup.
 */

import { toAiError } from '@/server/aegis/errors';
import type { CapabilityContext, CapabilityDef } from '@/server/aegis/registry';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { executeToolCall } = require('@/server/ai/ai/aiToolRouter');

export type AnalyticsSpec = {
  id: string;
  domain: string;
  description: string;
  params: Record<string, { type: 'string' | 'number' | 'boolean'; description: string; required?: boolean }>;
};

const PERIOD = {
  period: { type: 'string' as const, description: 'Time period (e.g. today, this_week, this_month, this_year).' },
};

export const ANALYTICS_SPECS: AnalyticsSpec[] = [
  { id: 'revenueSummary', domain: 'Analytics', description: 'Daily, weekly or monthly revenue with grouping.', params: { ...PERIOD, groupBy: { type: 'string', description: 'Group by: service, employee, customer, day, week, month, quarter, year.' } } },
  { id: 'revenueTrends', domain: 'Analytics', description: 'Revenue trends with growth and comparisons.', params: { ...PERIOD, comparison: { type: 'string', description: 'Comparison: previous_period, same_period_last_year.' } } },
  { id: 'serviceRevenueBreakdown', domain: 'Analytics', description: 'Revenue broken down by service, staff or customer.', params: { ...PERIOD, groupBy: { type: 'string', description: 'Group by: service, staff, customer.' } } },
  { id: 'revenueByEmployee', domain: 'Analytics', description: 'Revenue generated by each employee.', params: { ...PERIOD } },
  { id: 'revenueByService', domain: 'Analytics', description: 'Revenue by individual service offering.', params: { ...PERIOD } },
  { id: 'expenseAnalysis', domain: 'Analytics', description: 'Spending patterns, categories and cost trends.', params: { ...PERIOD, category: { type: 'string', description: 'Optional expense category filter.' } } },
  { id: 'unusualExpenses', domain: 'Analytics', description: 'Anomalous expenses deviating from normal patterns.', params: { ...PERIOD, threshold: { type: 'number', description: 'Deviation threshold in standard deviations.' } } },
  { id: 'profitAnalysis', domain: 'Analytics', description: 'Gross/net profit and margins with comparisons.', params: { ...PERIOD } },
  { id: 'profitMarginBreakdown', domain: 'Analytics', description: 'Margins by service or staff.', params: { ...PERIOD, groupBy: { type: 'string', description: 'Group by: service, staff.' } } },
  { id: 'customerIntelligence', domain: 'Analytics', description: 'Repeat customers, lifetime value, retention.', params: { ...PERIOD } },
  { id: 'topCustomers', domain: 'Analytics', description: 'Top-spending customers and revenue contribution.', params: { ...PERIOD, limit: { type: 'number', description: 'How many (default 10).' } } },
  { id: 'customerActivity', domain: 'Analytics', description: 'Visit frequency, last visits, engagement.', params: { ...PERIOD, daysInactive: { type: 'number', description: 'Days since last visit to count inactive.' } } },
  { id: 'serviceIntelligence', domain: 'Analytics', description: 'Service popularity, revenue contribution, demand.', params: { ...PERIOD } },
  { id: 'serviceProfitability', domain: 'Analytics', description: 'Most and least profitable services.', params: { ...PERIOD } },
  { id: 'salesSummary', domain: 'Analytics', description: 'Sales volume, transaction counts, average ticket.', params: { ...PERIOD } },
  { id: 'revenueForecast', domain: 'Analytics', description: 'Revenue forecast from historical trends.', params: { period: { type: 'string', description: 'Forecast horizon: next_month, next_quarter, next_year.' }, method: { type: 'string', description: 'Method: trend, seasonal, average.' } } },
  { id: 'expenseForecast', domain: 'Analytics', description: 'Expense forecast from spending history.', params: { ...PERIOD } },
  { id: 'demandForecast', domain: 'Analytics', description: 'Service demand forecast.', params: { ...PERIOD, serviceId: { type: 'string', description: 'Optional service identifier.' } } },
  { id: 'riskDetection', domain: 'Analytics', description: 'Business risks: revenue decline, expense spikes, churn, cash flow.', params: { ...PERIOD } },
  { id: 'cashFlowAnalysis', domain: 'Analytics', description: 'Inflows, outflows, net cash position.', params: { ...PERIOD } },
  { id: 'opportunityDetection', domain: 'Analytics', description: 'Growth, cost-reduction and upsell opportunities.', params: { ...PERIOD } },
  { id: 'staffPerformance', domain: 'Analytics', description: 'Staff revenue, services and satisfaction signals.', params: { ...PERIOD } },
  { id: 'businessHealthScore', domain: 'Analytics', description: 'Composite health score with reasons.', params: { ...PERIOD } },
  { id: 'executiveSummary', domain: 'Analytics', description: 'Executive summary with key metrics and recommendations.', params: { ...PERIOD } },
  { id: 'searchBusinessData', domain: 'Analytics', description: 'Search customers, transactions, services, expenses.', params: { query: { type: 'string', description: 'Search text.', required: true }, type: { type: 'string', description: 'Entity type: all, customers, transactions, services, expenses.' } } },
  { id: 'dashboardData', domain: 'Analytics', description: 'Dashboard bundle: revenue, profit, expenses, health, risks, forecasts, KPIs.', params: { ...PERIOD } },
];

const ANALYTICS_ROLES = ['shop_admin', 'staff', 'super_admin'];

/** Mirrors the CJS ROLE_TOOLS staff set so discovery never advertises denied tools. */
const STAFF_ANALYTICS = new Set([
  'revenueSummary',
  'salesSummary',
  'customerIntelligence',
  'customerActivity',
  'serviceIntelligence',
  'searchBusinessData',
]);

export function analyticsCapability(spec: AnalyticsSpec): CapabilityDef {
  return {
    id: spec.id,
    domain: spec.domain,
    description: spec.description,
    type: 'read',
    risk: 'low',
    params: spec.params,
    roles: STAFF_ANALYTICS.has(spec.id) ? ANALYTICS_ROLES : ['shop_admin', 'super_admin'],
    handler: async (ctx: CapabilityContext, args: Record<string, unknown>) => {
      const role = ctx.role === 'master' ? 'super_admin' : ctx.role;
      const authContext = { tenantId: ctx.tenantId, userId: ctx.userId, role };
      const result = await executeToolCall(authContext, { toolId: spec.id, args });
      if (!result || result.success !== true) {
        if (result && result.requiresConfirmation) {
          throw toAiError(new Error(`Tool "${spec.id}" requires human confirmation before execution.`));
        }
        throw toAiError(new Error(result?.error || `Analytics tool "${spec.id}" failed.`));
      }
      return result.result;
    },
  };
}
